default:
  token:
    iri_token: "hwTiQol6SJ8gsOiPFTefui23uFLlcgZ5lyRjhQxb"
  aws:
    id: "AKIAJU4COU6XIH3OMIAQ"
    password: "710NIG1grjK4/qLmpivEogkLDz5YvgFS1DvfSH8F"
    region: "eu-central-1"
  facebook_ads:
    token: "EAAE5tOBDoZA0BANYXZBptrdEq3va40dl92RhpyL70bs6Dq5Ayal3uEEZCmI5oqWUKqFdZAGOf5tGR0g4Q1sxUI1DwYfUYmWLBLqyC6ci1AQbqA6EsgzMf8UezUmZAJMEx2ZBPa3iM5dOh26mB5bQZA3hslHRIvBt3bJj0LjZA7wTE7pnWvZA74QUGuorjeZBCQ5Lu9owHQKsHB41cezMhyKB3A"
    
